# site settings
title: Developer Community TLV
subtitle: by the Community for the Community
email: cloudnativeisrael@gmail.com
description: The place to get info about the leading dev communities in TLV.
baseurl: # the subpath of your site, e.g. /blog
url: https://communitytlv.dev # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 3

# social settings
facebook_url:
github_url: https://gitlab.com/communitytlv
linkedin_url: https://www.linkedin.com/in/communityTLV
discord_url: https://discord.gg/fV4cMKQ
twitter_url: https://twitter.com/devrel_IL
devopsdays_url: https://devopsdaystlv.com
cloudnative_url: https://cloudnativeisrael.com
statscraft_url: http://statscraft.org.il
devseccon_url: https://devseccon.com
code-conduct_url: /code-of-conduct.html


markdown: kramdown
kramdown:
  input: GFM      

sass:
  style: compressed
