# site settings
title: Developer Community TLV
subtitle: by the Community for the Community
email: 
description: The place to get info about the leading dev communities in TLV.
baseurl: # the subpath of your site, e.g. /blog
url: https://tlvcommunity.dev # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 

# homepage tiles
tiles-source: "pages" # accepts "posts" or "pages"
tiles-count: 6

# social settings
facebook_url:
github_url: https://github.com/communitytlv
linkedin_url: https://www.linkedin.com/in/communityTLV
discord_url: https://discord.gg/jFqCBBG5xx
twitter_url: https://twitter.com/TLVCommunity
devopsdays_url: https://devopsdaystlv.com
cloudnative_url: https://cloudnativeisrael.com
statscraft_url: http://statscraft.org.il
devseccon_url: https://devseccon.com
code-conduct_url: /code-of-conduct.html


markdown: kramdown
kramdown:
  input: GFM      

sass:
  style: compressed
